FROM alpine
# Install iptables
RUN apk add --no-cache iptables
# Install golang
RUN apk add --no-cache go
# Install git
RUN apk add --no-cache git
# Install docker
RUN apk add --no-cache docker

# Copy the source code
COPY . /app
# Set the working directory
WORKDIR /app
# Build the binary
RUN go build -o ./bin/docknat ./cmd/docknat
# Go to the bin directory
WORKDIR /app/bin
# Run the binary
CMD ["sh"]
